"""KernelBuilder Python codegen backend.

Walks the post-Phase-4 IR (memref + scf + linalg + arith, with nkipy
annotations) and emits equivalent ``kernel_builder`` Python source code as
text — the same IR the NISA backend consumes (after pass 23, before the
``py:linalg-to-nisa`` pass).

Unlike the NISA backend, this one only *reads* the IR, so it uses the upstream
``mlir.ir`` bindings directly (see ``irutils``) and has no dependency on the
NKI wheel's builders.

Public entry point: :func:`linalg_to_kernelbuilder`.
"""

from __future__ import annotations

from mlir import ir as up_ir  # type: ignore[import-not-found]

from .api import get_api
from .emitter import Emitter
from . import irutils


def linalg_to_kernelbuilder(
    mlir_text: str,
    kernel_name: str,
    target: str = "trn2",
    api_version: str = "v1",
) -> str:
    """Translate post-Phase-4 MLIR to kernel_builder Python source (text -> text).

    Args:
        mlir_text: post-Phase-4 MLIR (memref+scf+linalg+arith+func).
        kernel_name: name for the generated Python function. The MLIR func's
            own ``sym_name`` is used if this is falsy.
        target: hardware target tag (recorded in a header comment for now).
        api_version: which :class:`~.api.KernelBuilderAPI` version to render.

    Returns:
        A string of valid Python source defining one function per ``func.func``
        in the module.
    """
    api = get_api(api_version)

    ctx = up_ir.Context()
    ctx.load_all_available_dialects()
    ctx.allow_unregistered_dialects = True
    with ctx:
        module = up_ir.Module.parse(mlir_text)
        gen = _ModuleEmitter(module, api, kernel_name, target)
        return gen.run()


class _ModuleEmitter:
    """Drives emission for one module: header, imports, one fn per func.func."""

    def __init__(self, module, api, kernel_name: str, target: str) -> None:
        self.module = module
        self.api = api
        self.kernel_name = kernel_name
        self.target = target
        self.em = Emitter()
        # SSA value -> generated Python variable name, rebuilt per function.
        self.names: dict = {}

    def run(self) -> str:
        for stmt in self.api.imports():
            self.em.add_import(stmt)

        funcs = irutils.func_ops(self.module)
        for i, func in enumerate(funcs):
            if i:
                self.em.blank()
                self.em.blank()
            self._emit_func(func)
        return self.em.getvalue()

    # -- function ----------------------------------------------------------

    def _emit_func(self, func) -> None:
        self.names = {}
        name = self.kernel_name or irutils.func_name(func)
        inputs, results = irutils.func_signature(func)

        block = func.regions[0].blocks[0]
        params = []
        for idx, arg in enumerate(block.arguments):
            pname = self.em.reserve_name(f"input_{idx}")
            self.names[arg] = pname
            params.append(pname)

        self.em.comment(f"Generated by nkigen kernelbuilder backend (target={self.target}).")
        self.em.line(f"def {name}({', '.join(params)}):")
        with self.em.indent():
            self._emit_block(block)

    # -- block / op dispatch ----------------------------------------------

    def _emit_block(self, block) -> None:
        # A Python block needs at least one *executable* statement; comments
        # alone are not enough. Track whether any real statement was emitted
        # and fall back to `pass` so the output always parses.
        emitted_stmt = False
        for op in block.operations:
            if self._emit_op(op):
                emitted_stmt = True
        if not emitted_stmt:
            self.em.line("pass")

    def _emit_op(self, op) -> bool:
        """Emit one op. Returns True if it produced an executable statement.

        Phase 1 establishes the dispatch skeleton; later phases fill in the
        handlers (memory, compute, control flow). Unhandled ops are surfaced
        as a TODO comment rather than silently dropped, so gaps are visible in
        the generated source — but a comment is not a statement, so it does not
        by itself satisfy a block.
        """
        name = op.operation.name
        handler = _DISPATCH.get(name)
        if handler is not None:
            return handler(self, op)
        # Terminators / structural ops we intentionally skip without noise.
        if name in _SILENT_SKIP:
            return False
        self.em.comment(f"TODO unhandled op: {name}")
        return False


# Op handlers are registered by the emit_* modules (Phases 2-4). For Phase 1
# the table is empty; the walker emits TODO comments for every op, producing a
# syntactically valid but not-yet-functional skeleton.
_DISPATCH: dict = {}

# Structural ops that produce no standalone statement in the generated code.
_SILENT_SKIP = {
    "func.return",
    "scf.yield",
    "linalg.yield",
    "arith.constant",
}


__all__ = ["linalg_to_kernelbuilder"]
